---
title: "Project Trial"
author: "Emma Brockman"
date: "2023-03-30"
output: html_document
---
# The following data set is an example data set to establish some basic skills within RMarkdown. The goal for this is basic exercise to calculate the mean for a given column, ignoring the unknown (NA) values. This was a helpful website: https://www.statology.org/r-mean-of-column/
> df <- data.frame(drug1 = c(4,5,6, NA), drug2 = c(6,7,8, NA), drug3 = c(8, 9, 10, NA))
> mean(df$drug1, na.rm=TRUE)
[1] 5
# The goal for the project as a whole is to analyze Shea's capstone data, which is data collected from white tailed deer in Oklahoma.
# The data will be entered from an excel file that has been created and analyzed using a T-test to measure the P-value and the Hardy-Weinberg Equilibrium to measure allele frequency. Averages of each numberic value column will also be established.
# The following is an upload of the excel data sheet file that we are using. This was a helpful website: https://community.rstudio.com/t/load-excel-file-into-rmarkdown/103020/3  
[OBU data (1).xlsx](https://github.com/emmabrockman4/ComputingProject/files/11115999/OBU.data.1.xlsx) 
---{r}
library(readxl)
OBU data <- read_excel("OBU data (1).xlsx")
---
# From this point on is the steps required to perform a ttest in Jupyter Lab
# import the data
import pandas as pd
from scipy.stats import ttest_ind
data = pd.read_csv('capstonedatacomputing.csv')
# make sure data has been imported
data.head()
# define the columns
column1 = data['SA']
column2 = data['PO']
# make a condition for only values desired to be put into the ttest
condition = (data['SA'] > 0.5) & (data['PO'] > 0.5)
# perform the ttest and print the results
t_statistic, p_value = stats.ttest_ind(column1[condition], column2[condition])
print("T-statistic: ", t_statistic)
print("P-value: ", p_value)
# overall analysis: The ttest was very easy to perform in Jupyter lab. The only problem that forshadowed wa that it did not require for the specifications of a ttest. This may rise to be an issue because there are several possibilites that effect the results of a ttest. Some of these options are 1-tailed,2-tailesd, and paired. These three differetn options for doing a ttest can provide a very wide array of numbers for the p-value and t-statistic. Overrall this language was very easy to use but may prove to be a little to easy and not desireably specific.
-----
# t test for SA and PO in R
# this is how a t test was ran in R

data <- read.csv("SAvsPO1.csv", header = TRUE, sep = ",")

library(ggplot2)

t.test(zoi ~ drug, data = SAvsPO1, var.equal = TRUE, paired = FALSE)
Two Sample t-test

data:  zoi by drug
t = 0.33229, df = 10, p-value =
  0.7465
alternative hypothesis: true difference in means between group PO and group SA is not equal to 0
95 percent confidence interval:
  -11.71525  15.82192
sample estimates:
  mean in group PO mean in group SA 
15.66500         13.61167 

#The ttest was really easy and simple to do in R versus jupyter lab. There is also more freedom in R to do one and two tailed tests in R. It was also much simpler because I simply had to import data and run the test, rather than go through the hassle of defining the columns.
